### ISSUE TITLE
What's the meaning of this paragraph

### ISSUE THREAD

**Issue by xiepengyue** [mfigurnov/sact#5]
Recall that the residual function consists of a stack of 1 × 1, 3 × 3 and 1 × 1 convolutional layers. **The first convolutional layer has to be evaluated in the positions obtained by dilating the active positions set with a 3 × 3 kernel.** The second and third layers need to be evaluated just in the active positions.

**Comment by mfigurnov** [comment]
Let's say that we are interested in computing the outputs of a convolutional layer in positions defined by a binary mask M (aka active positions set). Which inputs of the convolutional layer do we need to know to do that? That's called the receptive field of the layer. To compute it, we can do max-pooling (dilation) of the mask M with stride 1 and k x k kernel, where k is the kernel size of the convolutional layer. That's because if there is *any* active position within a k x k neighborhood, we need to know the value in this position. We apply this idea to a residual function and get what is described in the paragraph (after noting that 1x1 max-pooling is a no-op).

The code to do that is located here: https://github.com/mfigurnov/sact/blob/master/imagenet_model.py#L56 . See the `output_mask` arguments of convolutional layer.

**Comment by xiepengyue** [comment]
In SACT, you said ‘we simply copy the previous value for the inactive spatial positions’, so I think the output channel must be equal to input channel so that we can copy, yes?   And in your code, the ResNet34 was applied with 2 conv (3x3, 3x3) in each residual unit, it’s no problem since the same channel between input and output. But for ResNet50?  Recall that the residual function consists of a stack of 1 × 1, 3 × 3 and 1 × 1 convolutional  Layers, and the channel is not always equal, so what should I do in this case?

**Comment by mfigurnov** [comment]
A residual unit is a function `y = x + f(x)` (an exception is the first unit of every block, see below). The copying/masking simply means that we use a function `y = x + f(x) * M`, where the multiplication happens element-wise with broadcasting over channels. For active spatial positions, the result is `y_ij = x_ij + f_ij(x)`, and for inactive positions `y_ij = x_ij`.

Now, we need to compute the value of `f(x) * M`. Let's say `f(x) = conv1(conv2(conv3(x)))`, then `f(x) * M = conv1(conv2(conv3(x) * M3) * M2) * M`, where M2 and M3 are the dilated masks. The operation of `conv(x) * M` can be implemented efficiently using perforated conv layer.  Since we multiply/perforate using a mask over spatial positions and broadcast over channels, the changing number of channels is not a problem.

All of this requires that `shape(x) = shape(y)`. It is the case for all residual units except the first one in every block where the downsampling happens. However, we always compute all the values in the first unit of a block, so there is no perforation happening.

Hope this helps.

**Comment by xiepengyue** [comment]
Sorry， I still have a question. The residual unit function y=x+f(x), the ‘x’ is the original shortcut of ResNet. When use y=x+f(x)*M, and for active spatial positions’ result is y_ij = x_ij +f_ij(x), it’s ok. But for inactive positions y_ij = x_ij, here the x_ij isn’t from shaortcut ‘x’? Or it seems that we lose the part of inactive positions in result?

**Comment by mfigurnov** [comment]
Oops, missed your question. `x` is the shortcut connection in both cases, it's just the input of the residual unit. I don't see how this results in loss of inactive positions, sorry :( Could you clarify?
